
## Static graph (TensorFlow 1.x) vs Eager execution (TensorFlow 2.0)

![alt text](https://www.tensorflow.org/images/tensors_flowing.gif)
*Image take from: https://www.tensorflow.org/guide/graphs*


## TensorFlow 1.X




### Installing TensorFlow 1.X



In [ ]:
!pip install tensorflow-gpu==1.13.1

     |████████████████████████████████| 345.2MB 49kB/s 


In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'1.13.1'

### Variables and constants in TF 1.x

#### Variables

In [ ]:
#Initialize normal Variable in tf 1.x
variable = tf.Variable([[30, 20], [10, 45]])

In [ ]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [ ]:
#Getting shape of the variable
variable.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [ ]:
#Performing addition operation on the tensor produces another tf.Tensor object
variable + 2

<tf.Tensor 'add_1:0' shape=(2, 2) dtype=int32>

In [ ]:
#If a session is not initialized we cannot access values in the Variable/Tensor
variable.eval()

ValueError: ignored

In [ ]:
#Able to slice a variable, but we are still not able to retrive values from it
variable[:1]

<tf.Tensor 'strided_slice_2:0' shape=(1, 2) dtype=int32>

#### Getting values from variables

In [ ]:
#Initialize session
session = tf.Session()

In [ ]:
#Initialize ALL variables for the session
session.run(tf.global_variables_initializer())

In [ ]:
#Run the eval method on the evironment with provided session to retrive values from it
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

#### Constants/Tensors

In [ ]:
#Define a TensorFlow constant matrix
tensor = tf.constant([[23, 4], [32, 51]])

In [ ]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [ ]:
#We are still not able to get the real value without defining a session
tensor.eval()

ValueError: ignored

#### Getting values from constants

In [ ]:
session = tf.Session()

In [ ]:
session.run(tf.global_variables_initializer())

In [ ]:
#Fatching the tensor from the tensor graph/session
tensor_value = session.run(tensor)

In [ ]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

## TensorFlow 2.0

### Installing TensorFlow 2.0

In [8]:
# Not needed anymore do not run this!
!pip install tensorflow-cpu==2.9.1-alpha0

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
ERROR: Could not find a version that satisfies the requirement tensorflow-cpu==2.9.1-alpha0 (from versions: 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0, 2.8.1, 2.8.2, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1)
ERROR: No matching distribution found for tensorflow-cpu==2.9.1-alpha0


In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.9.1'

### Constants/Tensors

In [5]:
#Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [4]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [6]:
#Getting shape of a tensor; result is the shape of the tensor
tensor_20.shape

TensorShape([2, 2])

### Getting values from constants

In [7]:
#Getting values straight from a TensorFlow constant to numpy - without sesion
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [9]:
#We are able to convert a numpy matrix back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])

In [10]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [11]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Operations with constants/tensors

In [12]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Addition between scalar and tensor

In [13]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplication between scalar and tensor

In [14]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Using Numpy functions on TensorFlow tensors

In [16]:
#Squaring all numbers in a tensorflow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [28]:
#Square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product between two tensors

In [29]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Operations with variables

In [18]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Getting raw value from the variable

In [19]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Changing specific value in the TensorFlow variable

In [20]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [21]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Strings in TensorFlow 2.0

In [30]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

#### Simple string operations

In [31]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [32]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

### Storing arrays of strings

In [33]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [34]:
#How to iterate through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


### Handling Devices in TensorFlow 2.0

#### CPU

In [27]:
with tf.device("/cpu:0"):
    tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [ ]:
tf_string_array.device

'/job:localhost/replica:0/task:0/device:CPU:0'

#### GPU

In [ ]:
if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
    print(tf_string_array.device)